# Generated by Django 3.2.6 on 2021-08-14 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tag_name', models.CharField(max_length=20, unique=True)),
                ('category_tag_description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['category_tag_name'],
            },
        ),
        migrations.CreateModel(
            name='PremiseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, unique=True)),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(99)])),
                ('measured_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measurement_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('contracted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('facade_length', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('fitout_condition', models.BooleanField(default=False)),
                ('electric_capacity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cooling_capacity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('water_supply', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PremiseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('type_description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('needed_premise_type', models.CharField(max_length=30)),
                ('contact_person_name', models.CharField(max_length=100, null=True)),
                ('contact_person_position', models.CharField(max_length=100, null=True)),
                ('contact_person_email', models.EmailField(max_length=254, null=True)),
                ('contact_person_phone', models.PositiveBigIntegerField(null=True)),
                ('contact_person_mobile1', models.PositiveBigIntegerField(null=True)),
                ('contact_person_mobile2', models.PositiveBigIntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('retail_premise_type', models.CharField(max_length=30)),
                ('needed_min_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('needed_max_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('needed_ceiling_height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('needed_facade_length', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('needed_fitout_condition', models.BooleanField(default=False)),
                ('needed_electric_capacity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('needed_cooling_capacity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('needed_water_supply', models.BooleanField(default=False)),
                ('needed_additional_requirements', models.TextField(blank=True, max_length=500, null=True)),
                ('legal_name', models.CharField(max_length=100)),
                ('tax_id', models.BigIntegerField(default=0, unique=True)),
                ('signing_person_name', models.CharField(max_length=200, null=True)),
                ('signing_person_position', models.CharField(max_length=200, null=True)),
                ('legal_address', models.CharField(max_length=200, null=True)),
                ('postal_address', models.CharField(max_length=200, null=True)),
                ('kpp', models.BigIntegerField(null=True)),
                ('bik', models.CharField(max_length=9)),
                ('bank_name', models.CharField(max_length=100)),
                ('current_account', models.CharField(max_length=40)),
                ('correspondent_account', models.CharField(max_length=40, null=True)),
                ('ogrn', models.CharField(max_length=15, null=True)),
                ('okpo', models.CharField(max_length=10, null=True)),
                ('registration_authority', models.CharField(max_length=100, null=True)),
                ('legal_entity_certificate_number', models.CharField(max_length=100, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('brands', models.ManyToManyField(to='api.Brand')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_contract_number', models.CharField(max_length=50, null=True, unique=True)),
                ('contracted_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract_signing_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('rent_start_date', models.DateField(default=django.utils.timezone.now)),
                ('stop_billing_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('premise_return_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('duration_years', models.IntegerField(null=True)),
                ('duration_months', models.IntegerField(null=True)),
                ('duration_days', models.IntegerField(null=True)),
                ('rent_fee_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('service_fee_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('marketing_fee_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('turnover_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('CA_utilities_compensation_fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('utilities_compensation_type', models.CharField(choices=[('By counters', 'By Counters'), ('Fixed', 'Fixed'), ('None', 'None')], default='By counters', max_length=20, null=True)),
                ('CA_utilities_compensation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Proportional to leased area', 'Proportional Leased'), ('Proportional to GLA', 'Proportional Gla'), ('None', 'None')], default='Proportional to leased area', max_length=50, null=True)),
                ('rent_fee_indexation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable')], default='CPI', max_length=10, null=True)),
                ('service_fee_indexation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable')], default='Fixed', max_length=10, null=True)),
                ('marketing_fee_indexation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable')], default='Fixed', max_length=10, null=True)),
                ('utilities_compensation_fixed_indexation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable')], default='Fixed', max_length=10, null=True)),
                ('CA_utilities_compensation_fixed_indexation_type', models.CharField(choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable')], default='Fixed', max_length=10, null=True)),
                ('rent_fee_indexation_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('service_fee_indexation_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('marketing_fee_indexation_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('utilities_compensation_fixed_indexation_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('CA_utilities_compensation_fee_fixed_indexation_type_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('act_of_transfer_signed', models.BooleanField(default=False)),
                ('act_of_transfer_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('rent_fee_advance_payment_day', models.IntegerField(default=10, null=True)),
                ('service_fee_advance_payment_day', models.IntegerField(default=10, null=True)),
                ('marketing_fee_advance_payment_day', models.IntegerField(default=10, null=True)),
                ('CA_utilities_compensation_fee_fixed_payment_day', models.IntegerField(default=10, null=True)),
                ('utilities_compensation_fixed_payment_day', models.IntegerField(default=10, null=True)),
                ('guarantee_deposit_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank guarantee', 'Bank Guarantee'), ('Corporate guarantee', 'Corporate Guarantee'), ('None', 'None')], default='Cash', max_length=25, null=True)),
                ('guarantee_deposit_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('guarantee_deposit_number_of_months', models.PositiveBigIntegerField(null=True)),
                ('guarantee_deposit_provided', models.BooleanField(default=False)),
                ('guarantee_bank_guarantee_expiration_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('advance_payment_required', models.BooleanField(default=None, null=True)),
                ('advance_payment_paid', models.BooleanField(default=None, null=True)),
                ('advance_payment_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('insurance_required', models.BooleanField(default=None, null=True)),
                ('insurance_provided', models.BooleanField(default=None, null=True)),
                ('insurance_expiration_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.brand')),
                ('premise_id', models.ManyToManyField(to='api.PremiseMain')),
                ('tenant_contractor_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tenantcontractor')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category_tag',
            field=models.ManyToManyField(to='api.CategoryTag'),
        ),
    ]
