# Generated by Django 3.2.11 on 2023-02-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='gba',
        ),
        migrations.RemoveField(
            model_name='building',
            name='gla',
        ),
    ]
