# Generated by Django 3.2.6 on 2021-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210814_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='premisemain',
            name='premise_type',
            field=models.CharField(default='retail_premise', max_length=50, unique=True),
        ),
    ]
