# Generated by Django 3.2.6 on 2021-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_premisetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premisemain',
            name='premise_type',
            field=models.CharField(default='retail_premise', max_length=50),
        ),
    ]
