# Generated by Django 3.2.6 on 2021-08-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_premisemain_premise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premisemain',
            name='premise_type',
        ),
    ]
