# Generated by Django 3.2.6 on 2021-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_premisemain_premise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='premisemain',
            name='premise_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
