# Generated by Django 3.2.6 on 2021-08-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_premisemain_premise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontractor',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='bik',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='brands',
            field=models.ManyToManyField(null=True, to='api.Brand'),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='current_account',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='legal_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='needed_max_area',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='needed_min_area',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='retail_premise_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
