# Generated by Django 3.2.6 on 2021-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210817_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='brands',
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='brands',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
