# Generated by Django 3.2.6 on 2021-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210817_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontractor',
            name='contact_person_mobile1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='contact_person_mobile2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantcontractor',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
