# Generated by Django 3.2.6 on 2021-08-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210817_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContractorContacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_position', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_mobile1', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_mobile2', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('tenant_contractor_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tenantcontractor')),
            ],
        ),
    ]
