# Generated by Django 3.2.6 on 2021-08-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tenantcontractorcontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontractorcontacts',
            name='description',
        ),
    ]
