# Generated by Django 3.2.6 on 2021-08-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_tenantcontractorcontacts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontractorcontacts',
            name='tenant_contractor_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenantcontractor'),
        ),
    ]
