# Generated by Django 3.2.6 on 2021-08-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tenantcontractorcontacts_tenant_contractor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_mobile1',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_mobile2',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_phone',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='contact_person_position',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='description',
        ),
    ]
