# Generated by Django 3.2.6 on 2021-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210830_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcontractor',
            name='brands_id',
            field=models.ManyToManyField(to='api.Brand'),
        ),
    ]
