# Generated by Django 3.2.6 on 2021-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_brand_brand_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_category_tag',
            field=models.ManyToManyField(blank=True, null=True, to='api.CategoryTag'),
        ),
    ]
