# Generated by Django 3.2.6 on 2021-11-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_brand_brand_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_additional_requirements',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_ceiling_height',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_cooling_capacity',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_electric_capacity',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_facade_length',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_fitout_condition',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_max_area',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_min_area',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='needed_water_supply',
        ),
        migrations.RemoveField(
            model_name='tenantcontractor',
            name='retail_premise_type',
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_additional_requirements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_cooling_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_electric_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_facade_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_fitout_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_max_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_min_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='needed_water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='retail_premise_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
