# Generated by Django 3.2.6 on 2021-11-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211122_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_additional_requirements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_cooling_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_electric_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_fitout_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_max_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_min_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tenantcontractor',
            name='needed_water_supply',
            field=models.BooleanField(default=False),
        ),
    ]
