# Generated by Django 3.2.6 on 2021-12-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211218_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcontract',
            old_name='CA_utilities_compensation_fee_fixed_payment_day',
            new_name='CA_utilities_compensation_fee_payment_day',
        ),
    ]
