# Generated by Django 3.2.6 on 2021-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_ca_utilities_compensation_fee_fixed_payment_day_rentcontract_ca_utilities_compensation_fee_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='utilities_cold_water_compensation_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='utilities_electricity_compensation_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='utilities_gas_compensation_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='utilities_hot_water_compensation_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
