# Generated by Django 3.2.6 on 2021-12-18 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20211218_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcontract',
            name='guarantee_deposit_number_of_months',
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='advance_payment_contract_providing_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='guarantee_deposit_contract_providing_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='insurance_contract_providing_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='advance_payment_required',
            field=models.CharField(choices=[('Required', 'Required'), ('Not required', 'Not Required')], default='Required', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='insurance_required',
            field=models.CharField(choices=[('Required', 'Required'), ('Not required', 'Not Required')], default='Required', max_length=25, null=True),
        ),
    ]
