# Generated by Django 3.2.6 on 2022-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_rentcontract_contracted_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='marketing_fee_advance_payment_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_fee_advance_payment_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='service_fee_advance_payment_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_data_providing_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_fee_payment_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
