# Generated by Django 3.2.6 on 2022-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='CA_utilities_compensation_fee_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='marketing_fee_advance_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_fee_advance_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='service_fee_advance_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_data_providing_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_fee_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_fee_period',
            field=models.CharField(blank=True, choices=[('1_month', 'Month1'), ('3_months', 'Month3'), ('6_months', 'Month6'), ('12_months', 'Month12')], default='1_month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='utilities_cold_water_compensation_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='utilities_electricity_compensation_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='utilities_gas_compensation_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='utilities_hot_water_compensation_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
    ]
