# Generated by Django 3.2.6 on 2022-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220105_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='insurance_required',
            field=models.CharField(blank=True, choices=[('Required', 'Required'), ('Not required', 'Not Required')], default='Required', max_length=25, null=True),
        ),
    ]
