# Generated by Django 3.2.6 on 2022-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_rentcontract_insurance_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='act_of_transfer_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='contract_signing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_start_date',
            field=models.DateField(null=True),
        ),
    ]
