# Generated by Django 3.2.6 on 2022-01-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220105_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='act_of_transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='contract_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='contract_signing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='contracted_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='premise_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='stop_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
