# Generated by Django 3.2.6 on 2022-01-06 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220105_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premisemain',
            name='measurement_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='advance_payment_contract_providing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='guarantee_bank_guarantee_expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='guarantee_deposit_contract_providing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='insurance_contract_providing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='insurance_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
