# Generated by Django 3.2.11 on 2022-01-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220124_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
