# Generated by Django 3.2.11 on 2022-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220124_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='address_street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
