# Generated by Django 3.2.11 on 2022-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220124_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontractsetup',
            name='fixed_rent_calculation_method',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractonetimefee',
            name='one_time_fee_calculation_method',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractonetimefeesetup',
            name='one_time_fee_calculation_method',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfee',
            name='periodical_fee_calculation_method',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfeesetup',
            name='periodical_fee_calculation_method',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractsetup',
            name='building_id',
            field=models.ManyToManyField(blank=True, null=True, to='api.Building'),
        ),
    ]
