# Generated by Django 3.2.11 on 2022-01-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20220124_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantcontractor',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='tenantcontractorcontacts',
            options={'ordering': ['contact_person_name']},
        ),
    ]
