# Generated by Django 3.2.11 on 2022-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20220125_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontractsetup',
            name='fixed_rent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
