# Generated by Django 3.2.11 on 2022-01-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rentcontractsetup_fixed_rent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontractsetup',
            name='fixed_rent_calculation_object',
            field=models.CharField(choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
    ]
