# Generated by Django 3.2.11 on 2022-01-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rentcontractsetup_fixed_rent_calculation_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontractsetup',
            name='fixed_rent_prepayment_or_postpayment',
            field=models.CharField(choices=[('Prepayment', 'Prepayment'), ('Postpayment', 'Postpayment')], default='Prepayment', max_length=20, null=True),
        ),
    ]
