# Generated by Django 3.2.11 on 2022-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20220201_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcontractsetup',
            old_name='CA_utilities_compensation_fee_payment_day',
            new_name='CA_utilities_compensation_fee_advance_payment_day',
        ),
        migrations.AddField(
            model_name='rentcontractsetup',
            name='CA_utilities_compensation_fee_post_payment_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='rentcontractsetup',
            name='CA_utilities_compensation_fee_prepayment_or_postpayment',
            field=models.CharField(choices=[('Prepayment', 'Prepayment'), ('Postpayment', 'Postpayment')], default='Prepayment', max_length=20, null=True),
        ),
    ]
