# Generated by Django 3.2.11 on 2022-02-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20220201_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcontractsetup',
            name='fixed_rent_calculation_object',
        ),
    ]
