# Generated by Django 3.2.11 on 2022-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20220202_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontractsetup',
            name='CA_utilities_compensation_fee_prepayment_or_postpayment',
            field=models.CharField(blank=True, choices=[('Prepayment', 'Prepayment'), ('Postpayment', 'Postpayment')], default='Prepayment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractsetup',
            name='CA_utilities_compensation_fixed_indexation_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable'), ('Non_Indexable', 'Non Indexable')], default='Fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractsetup',
            name='CA_utilities_compensation_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Proportional_to_GLA', 'Proportional Gla'), ('Proportional_to_leased area', 'Proportional Leased'), ('None', 'None')], default='Proportional_to_GLA', max_length=50, null=True),
        ),
    ]
