# Generated by Django 3.2.11 on 2022-02-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20220212_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcontractsetup',
            name='building_id',
        ),
        migrations.AddField(
            model_name='rentcontractsetup',
            name='building_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.building'),
        ),
    ]
