# Generated by Django 3.2.11 on 2022-02-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20220217_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontractonetimefee',
            name='rent_contract_additional_agreement_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement'),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfee',
            name='rent_contract_additional_agreement_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement'),
        ),
        migrations.RemoveField(
            model_name='rentcontractutilityfee',
            name='counter_id',
        ),
        migrations.AddField(
            model_name='rentcontractutilityfee',
            name='counter_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.counter'),
        ),
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='rent_contract_additional_agreement_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement'),
        ),
    ]
