# Generated by Django 3.2.11 on 2022-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20220221_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontractperiodicalfee',
            name='periodical_fee_prepayment_or_postpayment',
            field=models.CharField(blank=True, choices=[('Prepayment', 'Prepayment'), ('Postpayment', 'Postpayment')], default='Prepayment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentcontractutilityfee',
            name='compensation_fixed_fee_prepayment_or_postpayment',
            field=models.CharField(blank=True, choices=[('Prepayment', 'Prepayment'), ('Postpayment', 'Postpayment')], default='Prepayment', max_length=20, null=True),
        ),
    ]
