# Generated by Django 3.2.11 on 2022-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_additionalagreement_turnover_fee_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='CA_utilities_compensation_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Proportional_to_GLA', 'Proportional Gla'), ('Proportional_to_leased_area', 'Proportional Leased'), ('None', 'None')], default='Proportional_to_GLA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='guarantee_deposit_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank_guarantee', 'Bank Guarantee'), ('Corporate_guarantee', 'Corporate Guarantee')], default='Cash', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='turnover_fee_period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True),
        ),
    ]
