# Generated by Django 3.2.11 on 2022-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20220227_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontractonetimefee',
            name='one_time_fee_calculation_method',
            field=models.CharField(blank=True, choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractonetimefee',
            name='one_time_fee_payment_term',
            field=models.CharField(blank=True, choices=[('Fixed_date', 'Fixed Date'), ('Triggering_event_date', 'Triggering Event Date'), ('Not_fixed', 'Not Fixed')], default='Fixed_date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractonetimefee',
            name='one_time_fee_payment_triggering_event',
            field=models.CharField(blank=True, choices=[('Contract_signing_date', 'Contract Signing Date'), ('Premise_transfer_date', 'Act Of Transfer Date'), ('Start_of_commercial_activity', 'Rent Start Date')], default='Premise_transfer_date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfee',
            name='periodical_fee_calculation_method',
            field=models.CharField(blank=True, choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfee',
            name='periodical_fee_indexation_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable'), ('Non_Indexable', 'Non Indexable')], default='Fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractperiodicalfee',
            name='periodical_fee_payment_period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='compensation_calculation_period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='compensation_fixed_fee_indexation_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('CPI', 'Cpi'), ('Revisable', 'Revisable'), ('Non_Indexable', 'Non Indexable')], default='Fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='compensation_payment_period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('Using counter', 'Using Counter'), ('Fixed', 'Fixed'), ('None', 'None')], default='Using counter', max_length=20, null=True),
        ),
    ]
