# Generated by Django 3.2.11 on 2022-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20220227_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontractutilityfee',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('Using_counter', 'Using Counter'), ('Fixed', 'Fixed'), ('None', 'None')], default='Using_counter', max_length=20, null=True),
        ),
    ]
