# Generated by Django 3.2.11 on 2022-02-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_rentcontractutilityfee_compensation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcontractutilityfee',
            name='counter_id',
        ),
    ]
