# Generated by Django 3.2.11 on 2022-08-03 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0072_alter_rentcontractonetimefee_one_time_fee_contract_triggering_event_related_payment_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepPeriodicPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_calculation_method', models.CharField(blank=True, choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
