# Generated by Django 3.2.11 on 2022-08-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_stepperiodicpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepperiodicpayment',
            options={},
        ),
    ]
