# Generated by Django 3.2.11 on 2022-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_stepperiodicpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepperiodicpayment',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepperiodicpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stepperiodicpayment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
