# Generated by Django 3.2.11 on 2022-08-07 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0075_auto_20220803_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedRentStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('fixed_rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fixed_rent_calculation_period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True)),
                ('fixed_rent_calculation_method', models.CharField(blank=True, choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent_contract_additional_agreement_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalFeeStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('periodical_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('periodical_fee_payment_period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True)),
                ('periodical_fee_calculation_method', models.CharField(blank=True, choices=[('Per_sqm', 'Per Sqm'), ('Total', 'Total')], default='Per_sqm', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodical_fee_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rentcontractperiodicalfee')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentcontract',
            name='fixed_rent_payment_period',
        ),
        migrations.DeleteModel(
            name='StepPeriodicPayment',
        ),
        migrations.AddField(
            model_name='fixedrentstep',
            name='rent_contract_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rentcontract'),
        ),
        migrations.AddField(
            model_name='fixedrentstep',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
