# Generated by Django 3.2.11 on 2022-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20220807_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='fixed_rent_payment_period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True),
        ),
    ]
