# Generated by Django 3.2.11 on 2022-08-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_rentcontract_fixed_rent_payment_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicalfeestep',
            old_name='periodical_fee_payment_period',
            new_name='periodical_fee_calculation_period',
        ),
    ]
