# Generated by Django 3.2.11 on 2022-08-24 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0078_rename_periodical_fee_payment_period_periodicalfeestep_periodical_fee_calculation_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoverFeeStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('turnover_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('turnover_fee_calculation_period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent_contract_additional_agreement_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement')),
                ('rent_contract_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rentcontract')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalFeeIndexationStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('periodical_fee_indexation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('periodical_fee_indexation_calculation_period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodical_fee_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rentcontractperiodicalfee')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedRentIndexationStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('fixed_rent_indexation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fixed_rent_indexation_calculation_period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('3_months', 'Months3'), ('6_months', 'Months6'), ('Year', 'Year')], default='Month', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent_contract_additional_agreement_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalagreement')),
                ('rent_contract_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rentcontract')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
