# Generated by Django 3.2.11 on 2023-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20230204_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='gba',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='gla',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
